apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: ecr-creds
      containers:
        - name: mysql
          image: 247437911316.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "passwors"
            - name: MYSQL_DATABASE
              value: "employees"
          ports:
            - containerPort: 3306