apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 247437911316.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "employees"
      ports:
        - containerPort: 3306