apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: employees
spec:
  containers:
  - name: webapp
    image: 247437911316.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
    ports:
    - containerPort: 8080